# Specifies the GHC version and set of packages available
resolver: lts-11.9

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- distributed-process-0.7.3
- distributed-process-extras-0.3.2
- distributed-process-systest-0.2.0
- rematch-0.2.0.0

# Override default flag values for local packages and extra-deps
flags: {}
