# Specifies the GHC version and set of packages available
resolver: lts-11.13

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- rematch-0.2.0.0
- exceptions-0.10.0
- network-transport-tcp-0.6.0 # works locally without it but doesn't pass CI
- git: https://github.com/haskell-distributed/distributed-process.git
  commit: d91a88f70c2cb6a6511283c5720bd9950fc3c55a
- git: https://github.com/haskell-distributed/distributed-process-systest.git
  commit: b4a6b646adb6c81725ddac4babcfc21b86944d98

# Override default flag values for local packages and extra-deps
flags: {}
