# Specifies the GHC version and set of packages available
resolver: lts-10.3

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/lorenzo/distributed-process-systest.git
    commit: 63671acfb1ff348ed6c59d08980a91d46273e734
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}
